### PR TITLE
Fix Node 24 compatibility: bump azure-pipelines-task-lib to 5.x

### LINKED ISSUE #154: Azure Pipelines Agent v4.269.0 (Node 24) breaks MicrosoftSecurityDevOps@1 v1.18.1: crypto.createCipher is not a function
Since upgrading the Azure Pipelines Agent to v4.269.0 (Node 24), pipelines that are decorated to run Microsoft Security DevOps (MSDO) fail with:

TypeError: crypto.createCipher is not a function
  at _exposeTaskLibSecret (azure-pipelines-task-lib/internal.js:923:29)
  ...

Root cause:
- Node.js removed crypto.createCipher() in v22 (DEP0106). This is why Node 24 throws "is not a function".
- The MSDO Azure DevOps task (MicrosoftSecurityDevOps@1, v1.18.1) still calls this removed API via azure-pipelines-task-lib.

Impact:
- Organization-wide impact if the task is injected via a pipeline decorator (no pipeline-level control to pin a different injected task version).

Environment:
- Azure Pipelines Agent: v4.269.0
- Node runtime: v24.x (agent default)
- MSDO task: MicrosoftSecurityDevOps@1 v1.18.1

### PR DESCRIPTION
**Pull request by DimaBir**
## Summary
- Bumps `azure-pipelines-task-lib` from `^4.13.0` to `^5.2.4` to fix `TypeError: crypto.createCipher is not a function` on Node 24 agents
- Bumps `azure-pipelines-tool-lib` from `^2.0.7` to `^2.0.12` to align with task-lib 5.x dependency

## Root cause
`azure-pipelines-task-lib` 4.x uses `crypto.createCipher()` in `_exposeTaskLibSecret()`, which was removed in Node.js v22 ([DEP0106](https://nodejs.org/api/deprecations.html#DEP0106)). The upstream fix replacing it with `createCipheriv()` shipped in [task-lib PR #1147](https://github.com/microsoft/azure-pipelines-task-lib/pull/1147) / v5.2.4+. Since `^4.x` never resolves to 5.x, a major version bump is required.

Fixes https://github.com/microsoft/security-devops-azdevops/issues/154

## Test plan
- [ ] `npm install` completes cleanly
- [ ] `npm run compile-and-test` passes
- [ ] Extension builds and runs successfully on an Azure Pipelines agent with Node 24

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by DimaBir** [comment]
Closing - PR should be created in Azure DevOps, not the GitHub mirror.
